version: '3.8'
services:
  flask:
    image: python:3.10-slim
    command: bash -c "pip install -r requirements.txt && flask run"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    ports:
      - "55580:80"
    depends_on:
      - flask
